feat: add ugly nvim config with lua
yuri-potatoq/dotfiles pull request #2
Opened 2022-08-27 22:55 UTC by yuri-potatoq

2022-08-27 22:58 UTC, alandev2 approved these changes

2022-08-27 22:59 UTC, arcticlimer requested changes

2022-08-27 22:59 UTC, arcticlimer commented on home/editors/nvim/lua/completion.lua
> +    { name = 'emoji' },
please no

2022-08-28 13:44 UTC, yuri-potatoq commented on home/editors/nvim/lua/completion.lua
> +    { name = 'emoji' },
i have no choice, sorry

2022-08-28 13:44 UTC, merged